# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    omit_local_variable_types: false
    prefer_final_fields: false
    prefer_collection_literals: false
    unnecessary_this: false
    curly_braces_in_flow_control_structures: false
    slash_for_doc_comments: false

analyzer:
#   exclude:
#     - path/to/excluded/files/**
